<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>021591ec-c9ef-4a6a-8d7d-9c7c00b62f27</UserSecretsId>
		
		
	</PropertyGroup>


	<ItemGroup>
		<!--<PackageReference Include="Fluent.Infrastructure" Version="2.0.0-beta-01" />-->


		<PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
		<PackageReference Include="Hangfire" Version="1.8.21" />
		<PackageReference Include="Hangfire.AspNetCore" Version="1.8.21" />
		<PackageReference Include="Hangfire.Dashboard.Basic.Authentication" Version="8.0.0" />
		<PackageReference Include="Hangfire.SqlServer" Version="1.8.21" />
		<PackageReference Include="MailKit" Version="4.13.0" />
		<PackageReference Include="Mapster" Version="7.4.0" />
		<PackageReference Include="Mapster.DependencyInjection" Version="1.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.19" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.19">
		  <PrivateAssets>all</PrivateAssets>
		  <includeassets>runtime; build; native; contentfiles; analyzers; buildtransitive</includeassets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="8.0.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
	</ItemGroup>

</Project>
